{
 "title": "btc",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BTC/USD",
   "type": "timeseries",
   "description": "Info about price of BTC/USD",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "price_btc",
     "columnTime": "trade_ts",
     "columnValue": "volume",
     "keyspace": "market",
     "table": "trades",
     "target": "SELECT price, ingestion_ts FROM market.trades WHERE symbol = 'BINANCE:BTCUSDT'"
    },
    {
     "alias": "volume_btc",
     "target": "SELECT volume, ingestion_ts FROM market.trades WHERE symbol = 'BINANCE:BTCUSDT'"
    }
   ]
  },
  {
   "title": "AVG BTC/USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "price_x_volume",
     "target": "SELECT avg_price_x_volume, ingestion_ts FROM market.run_10_s_avg WHERE symbol = 'BINANCE:BTCUSDT'"
    }
   ]
  },
  {
   "title": "ETH/USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "price_eth",
     "columnTime": "trade_ts",
     "columnValue": "value",
     "keyspace": "market",
     "table": "trades",
     "target": "SELECT price, ingestion_ts FROM market.trades WHERE symbol = 'BINANCE:ETHUSDT'"
    },
    {
     "alias": "volume_eth",
     "target": "SELECT volume, ingestion_ts FROM market.trades WHERE symbol = 'BINANCE:ETHUSDT'"
    }
   ]
  },
  {
   "title": "AVG ETH/USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "price_x_volume",
     "target": "SELECT avg_price_x_volume, ingestion_ts FROM market.run_10_s_avg WHERE symbol = 'BINANCE:ETHUSDT'"
    }
   ]
  },
  {
   "title": "DOGE/USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "price_doge",
     "target": "SELECT price, ingestion_ts FROM market.trades WHERE symbol = 'BINANCE:DOGEUSDT'"
    },
    {
     "alias": "volume_doge",
     "target": "SELECT volume, ingestion_ts FROM market.trades WHERE symbol = 'BINANCE:DOGEUSDT'"
    }
   ]
  },
  {
   "title": "AVG DOGE/USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "price_x_volume",
     "target": "SELECT avg_price_x_volume, ingestion_ts FROM market.run_10_s_avg WHERE symbol = 'BINANCE:DOGEUSDT'"
    }
   ]
  },
  {
   "title": "XRP/USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "price_xrp",
     "target": "SELECT price, ingestion_ts FROM market.trades WHERE symbol = 'BINANCE:XRPUSDT'"
    },
    {
     "alias": "volume_xrp",
     "target": "SELECT volume, ingestion_ts FROM market.trades WHERE symbol = 'BINANCE:XRPUSDT'"
    }
   ]
  },
  {
   "title": "AVG XRP/USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "price_x_volume",
     "target": "SELECT avg_price_x_volume, ingestion_ts FROM market.run_10_s_avg WHERE symbol = 'BINANCE:XRPUSDT'"
    }
   ]
  }
 ]
}